### ISSUE TITLE
RGW socket not detected

### ISSUE THREAD

**Issue by alram** [ceph/cephmetrics#10]
I have a RGW running on my machine but collectd log displayed:
```[2017-06-20 11:42:41] cephmetrics: Roles detected - mon:True osd:True rgw:False```

It seems there's an extra '.' in the regex. It tries to find ```/var/run/ceph/<cluster>-client.rgw.<hostname>.<maybe_something>.asok``` which in my case ends up being:
```/var/run/ceph/ceph-client.rgw.ceph..asok ```
https://github.com/pcuzner/cephmetrics/blob/master/cephmetrics.py#L42

**Comment by pcuzner** [comment]
The format of the glob expects to see the pid of the rgw following the hostname. This is what I see on downstream ceph-radosgw-10.2.2-15.

Should the glob simply be glob.glob('/var/run/ceph/ceph-client.rgw.*.asok') - this seems to cover sockets with pid and without pid.

Would this be more appropriate?

**Comment by alram** [comment]
Sounds good to me

**Comment by pcuzner** [comment]
this change is on magna123 - can you start radosgw and confirm this is resolved.

**Comment by alram** [comment]
Looks like magna123 is having some issues with the radosgw. It can't connect to the cluster. 
```2017-06-21 07:49:44.780891 7f5d0268c9c0  0 failed reading zonegroup info: ret -2 (2) No such file or directory```

It's looking for a few inexistent zonegroup objects  in .rgw.root. Seems like something is really broken on this cluster:
```# radosgw-admin zonegroup list
read_default_id : -2
{
    "default_info": "",
    "zonegroups": []
}```

**Comment by djgalloway** [comment]
This cluster was upgraded to RHCS 2.3 yesterday and I'm struggling to get the RGW service running again.

**Comment by djgalloway** [comment]
@alram I don't think the previous RGW setup was critical, important, or used.  I'm going to try rebuilding the RGW client setup from scratch.

**Comment by djgalloway** [comment]
@alram RGW is running again on magna123.

`srwxr-xr-x.  1 ceph ceph    0 Jun 26 17:41 ceph-client.rgw.magna123.asok`

Let me know if I can help with anything else.  I didn't mess with pools or anything.

**Comment by pcuzner** [comment]
@djgalloway thanks. rgw stats now showing in the dashboard. closing the issue
