### ISSUE TITLE
stopping and restarting mon causes issues in collectd 

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephmetrics#101]
The collector samples health stats from the mon admin socket. When the monitor is shutdown, the collector hits an exception which is picked up by collectd. collectd responds by suspending the collector over increasing intervals until the collector stops failing.

Goal : the collectors should
a) probe for the presence of the ceph-mon binary to determine role
b) if the socket returns an empty set simply retry on each get_stats call, preventing the collectd response

**Comment by zmc** [comment]
https://github.com/ceph/cephmetrics/pull/108
