### ISSUE TITLE
"Health History - Last 3 Days" graph is a little confusing

### ISSUE THREAD

**Issue by djgalloway** [ceph/cephmetrics#105]
It took some thinking but I'm guessing if the green line is above the yellow bar, the cluster's in HEALTH_WARN and HEALTH_ERR if above the red line?

Could the red and yellow lines be labeled?

Also why are there three of the same "Ceph Health" keys in the legend at the bottom?

![image](https://user-images.githubusercontent.com/11281208/29578663-0d46ba20-873e-11e7-8dcc-b2a84f714b58.png)

**Comment by pcuzner** [comment]
I thought the same thing about labelling the threshold lines, but AFAIK, Grafana doesn't support that. I've tried to explain the chart a bit more in the tooltip (i - top left).

You see 3 keys in the legend, because you're on an older chart (the current version should just show ine legend entry)

**Comment by pcuzner** [comment]
Closing - if there are any further questions please reopen
