### ISSUE TITLE
"At A Glance" view shows incorrect OSD out count

### ISSUE THREAD

**Issue by djgalloway** [ceph/cephmetrics#106]
The cephmetrics instance monitoring our Sepia cluster shows -1 OSDs out.  There is indeed one down but we have the noout flag set.

![image](https://user-images.githubusercontent.com/11281208/29578756-6a0ab1b2-873e-11e7-9c20-e26b0e9b8e23.png)

**Comment by pcuzner** [comment]
Yep - this is a bug. The 'out' value is calculated based on the other metrics and can't account for the setting of noout. If it's not helpful it should be removed - do you agree?

**Comment by djgalloway** [comment]
What are the other metrics?

Total OSDs minus In OSDs should suffice, no?

**Comment by pcuzner** [comment]
resolved in PR #119
