### ISSUE TITLE
Health alert flapping incorrectly

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#113]
During a cluster upgrade I observed some very strange flapping in the health alert. The health status itself was stable during this time:
<img width="1011" alt="screen shot 2017-09-07 at 2 06 24 pm" src="https://user-images.githubusercontent.com/58307/30182933-ce7b6710-93d5-11e7-9ad6-69a1aeeb541b.png">

Changing the alert condition from `last()` to `max()` appears to fix this.

**Comment by pcuzner** [comment]
fix merged
