### ISSUE TITLE
getting collectd error on mons after update

### ISSUE THREAD

**Issue by scheuk** [ceph/cephmetrics#115]
Unhandled python exception in read callback: KeyError: u'.intent-log'

Here's a list of pools on the cluster:
$ ceph osd pool ls
.intent-log
.log
.rgw
.rgw.buckets
.rgw.buckets.extra
.rgw.buckets.index
.rgw.control
.rgw.gc
.rgw.root
.usage
.users
.users.email
.users.swift
.users.uid

**Comment by pcuzner** [comment]
can you provide the traceback? Is this from the latest master or the test add-timeout branch?

**Comment by scheuk** [comment]
@pcuzner this is from the latest master, how do I get a traceback from the collectd plugin?

**Comment by zmc** [comment]
This is actually something I meant to introduce a while back. I just filed
a PR with the required change, but it's trivial to do it manually in the
meantime.

https://github.com/ceph/cephmetrics/pull/117

**Comment by scheuk** [comment]
@pcuzner here's the error:

Sep 13 15:17:11 mon1-lab-00.blah.com systemd[1]: Started Collectd statistics daemon.
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: Systemd detected, trying to signal readyness.
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: Initialization complete, entering read-loop.
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: Unhandled python exception in read callback: KeyError: u'.intent-log'
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: Traceback (most recent call last):
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: File "/usr/lib64/collectd/cephmetrics/cephmetrics.py", line 158, in read_callback
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: stats = CEPH.get_stats()
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: File "/usr/lib64/collectd/cephmetrics/cephmetrics.py", line 58, in get_stats
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: stats['mon'] = self.mon.get_stats()
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: File "/usr/lib64/collectd/cephmetrics/collectors/mon.py", line 601, in get_stats
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: pool_stats[pool_name], df_obj['stats'])
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: KeyError: u'.intent-log'
Sep 13 15:17:11 mon1-lab-00.blah.com collectd[11885]: read-function of plugin `python.cephmetrics' failed. Will suspend it for 20.000 seconds.

**Comment by scheuk** [comment]
ok digging into the code it looks like you do a `ceph osd pool stats --format json` or similar command, here's the output of that from my cluster:

[root@mon1-lab-00 ~]# ceph osd pool stats --format json

[{"pool_name":".intent-log","pool_id":45,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".log","pool_id":46,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".rgw","pool_id":47,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".rgw.buckets","pool_id":48,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".rgw.buckets.extra","pool_id":49,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".rgw.buckets.index","pool_id":50,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".rgw.control","pool_id":51,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".rgw.gc","pool_id":52,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".rgw.root","pool_id":53,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".usage","pool_id":54,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".users","pool_id":55,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".users.email","pool_id":56,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".users.swift","pool_id":57,"recovery":{},"recovery_rate":{},"client_io_rate":{}},{"pool_name":".users.uid","pool_id":58,"recovery":{},"recovery_rate":{},"client_io_rate":{}}]

**Comment by scheuk** [comment]
we are running ceph 2.4/ jewel 10.2.7
[root@mon1-lab-00 ~]# ceph -v
ceph version 10.2.7-32.el7cp (ef49626371ba965ec4d3f8eff67a811528c0a334)

**Comment by pcuzner** [comment]
@scheuk can you please try the latest master or rpms from download.ceph.com to confirm that this fixes your issue. Local tests have been successful.

**Comment by scheuk** [comment]
@pcuzner I just deployed the laster master last commit was <098fb9a59de0827b85f1dcbc4f36bce2220f96a0>

Now the plugin is saying it can't get the radosgw metric:

collectd[17360]: cephmetrics error: RGW - RGW socket not available...radosgw running?

**Comment by scheuk** [comment]
here's what in the socket directory:
[root@mon1-lab-00 ~]# ls -l /var/run/ceph/
total 0
srwxr-xr-x. 1 ceph ceph 0 Sep 12 13:50 ceph-client.rgw.mon1-lab-00.asok
srwxr-xr-x. 1 ceph ceph 0 Sep 12 13:50 ceph-mon.mon1-lab-00.asok

**Comment by pcuzner** [comment]
@scheuk looks like the socket names are different in your environment, and the glob pattern I'm using didn't find them. I've corrected this now on master - please refresh at least the rgw collector in your environment.

I have some dashboard updates in test at the moment, which may also hit master this week which you may find useful (rgw hosts up/down, osd hosts up/down)

**Comment by scheuk** [comment]
ok everything seem so to be working,
Thanks @pcuzner
