### ISSUE TITLE
The RGW workload page is missing some RGW hosts

### ISSUE THREAD

**Issue by scheuk** [ceph/cephmetrics#133]
We have 5 hosts running radosgw and the RGW workload page shows only 3, also some of the graphs also show only 3 hosts. see the image below:

![screen shot 2017-10-02 at 2 14 43 pm](https://user-images.githubusercontent.com/1770185/31092401-541e298e-a77c-11e7-9e50-5d42282fdf2a.png)

**Comment by pcuzner** [comment]
things to check 
1. look at the collectd-cephmetrics.log file on the missing hosts to confirm that it's detected the rgw role correctly
2. check the collectd conf to ensure it's not sending the data under the same hostname as one of the others (i.e. if the collectd.conf has a "Hostname" setting that clashes with one of the other nodes)
3. look in graphite web for the metrics. each rgw collector will show as a separate subtree
4. the rgw hosts are defined by a templating variable - if you added the hosts and data is being sent to graphite this definition may be out of date. Look at the templating definition of the dashboard for rgw_servers - it should be a list of hostnames...are they there? If not add them. 

let me know what you find. I suspect check '4' may be the the culprit.

**Comment by scheuk** [comment]
@pcuzner yes it was #4
Does that get set with ansible when it imports the template?

**Comment by scheuk** [comment]
@pcuzner I answered my own question
the template pulls in the [rgw] inventory group 
rgw_servers: [{% for fqdn in groups['rgws'] | default([]) %}{{ fqdn.split('.')[0] }},{% endfor %}]
