### ISSUE TITLE
graphite-web version

### ISSUE THREAD

**Issue by scheuk** [ceph/cephmetrics#145]
what version of graphite-web should be installed?

I current have:
graphite-web-0.9.15-1.el7scon.noarch
installed form the cephmetrics repo,

But I'm getting an error in the  Create Graphite DB tables task:

TASK [ceph-grafana : Create Graphite DB tables] ********************************
fatal: [mgmt1-lab-00]: FAILED! => {"changed": true, "cmd": ["/usr/bin/graphite-manage", "migrate", "--noinput"], "delta": "0:00:00.320624", "end": "2017-10-19 13:04:31.878732", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-10-19 13:04:31.558108", "stderr": "/usr/lib/python2.7/site-packages/graphite/settings.py:246: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security\n  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')\nUnknown command: 'migrate'\nType 'graphite-manage help' for usage.", "stdout": "", "stdout_lines": [], "warnings": []}

the `/usr/bin/graphite-manage migrate` command must be in a newer version of graphite-web?

**Comment by pcuzner** [comment]
I just checked the downstream repo too, and this is 0.9.15-1 too. What confuses me further is that our QA guys have deployed successfully !?! More digging required.

**Comment by zmc** [comment]
@scheuk Please check your `python-django` and `python-django-tagging` versions. The repo has `1.8.18-1.el7ost` and `0.3.6-1.el7ost` respectively, and I'm nearly certain you've got older versions installed.

**Comment by scheuk** [comment]
@zmc correct, I am seeing the older versions of django installed,
However, I'm not seeing 1.8.18-1.el7ost in the development repo as well:
https://chacra.ceph.com/r/cephmetrics/master/HEAD/rhel/7/flavors/default/noarch/

**Comment by zmc** [comment]
@scheuk oh, this makes more sense now. Those repos aren't being updated with updated pre-release packages for RHEL. @b-ranto / @pcuzner: We need to figure out how we should deliver them...

**Comment by b-ranto** [comment]
@zmc There are pretty much two ways to do that (well, three but...). We can either Require a specific version (well, `>=` a certain version) of the packages in the spec file or we can add an ansible `package` task with `state: latest` to the ansible scripts.

The former solution should be the preferred one but it requires us to build our own version of graphite-web as that is the package that actually requires these `python-django` packages (it is not difficult to do that, graphite-web already requires a version of python-django `>=` 1.3 so it would be a minor update).

Another "fix" would be to document it and say that you need to update the django packages manually.

**Comment by ltrilety** [comment]
Working for me with graphite-web-0.9.15-1.el7scon.noarch, no fails in the cephmetrics install.
BTW I have these installed:
python-django-1.8.18-1.el7ost.noarch
python-django-bash-completion-1.8.18-1.el7ost.noarch
python-django-tagging-0.3.6-1.el7ost.noarch

**Comment by b-ranto** [comment]
Hmm, I thought this was talking about upgrades but apparently it is not. They were trying to deploy with a mixture of old and new repositories.

FYI: I ~recently pushed a patch to our ansible scripts to remove the old repository file in production mode so we should be pretty much good to go. In case of upgrades, you should always update all the packages to the latest version available by the package manager.

btw: Do we have an upgrade guide from the old repositories? The customers should probably update the packages to their latest versions and re-run the ansible deployment scripts in that case.

**Comment by scheuk** [comment]
@b-ranto I saw that but when using `devel_mode: true`, the code will setup the development repo:

https://chacra.ceph.com/r/cephmetrics/master/HEAD/rhel/7/flavors/default/
And in those repos there is only the python-django-1.6.11-4.el7scon.noarch packages 
and the python-django-1.8.18-1.el7ost.noarch package is not in that repo.

So to simplify: the updated python-django-1.8.18-1.el7ost.noarch packages are not available publicly.

**Comment by b-ranto** [comment]
Since the #149 was merged, this should work even with the old packages, now. I guess we can close this. We could probably update the packages at some point but afaik, the repo is mostly deprecated.
