### ISSUE TITLE
SELinux issues with collectd

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#16]
See https://gist.github.com/zmc/e4cdaa1a72bdb34c46c0dacf8cc58fa8

**Comment by pcuzner** [comment]
I'd documented selinux as an issue in the install guide. When you generate a local policy to resolve, what does it look like - is it just collectd accessing the sockets in /var/run/ceph?

**Comment by pcuzner** [comment]
selinux blocks write_graphite too (look at magna123, Jun 21)
https://gist.github.com/pcuzner/049cc8fef1f49c533e0dac47fb66976e

**Comment by zmc** [comment]
I believe this is fixed by https://github.com/ceph/cephmetrics/commit/ac6ea525fa982215b09cea1a5f10b54469a1d7d6 and https://github.com/ceph/cephmetrics/pull/34

**Comment by zmc** [comment]
https://github.com/ceph/cephmetrics/pull/37 appears to have fixed the last remaining issue; I've checked after deploying with:
```
ansible -v -i ~/cephmetrics/inventory -m command -a '/sbin/ausearch -m avc -ts today 20:21' "osds,mons,mdss,rgws"
```

On the various clusters I'm looking at.
