### ISSUE TITLE
user login should go straight to our at a glance dashboard

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephmetrics#20]
We should push the user straight to our dashboard at login, to reduce the need to understand too much about the grafana UI

**Comment by pcuzner** [comment]
starred dashboards can be added as default dashboards. In our case we can assume there is only one org in grafana, and assign our dashboard as the default to the org, that way any users the customer creates lands on the same home page

Process is as follows (with curl);
get the at-a-glance dashboard
extract the dashboards id (mine was 16)
star the dashboard with 
curl -u admin:admin -H "Content-Type: application/json" -X POST http://localhost:3000/api/user/stars/dashboard/16

update the org using a json file (org.json)
{
	"name":"Main Org.", 
	"homeDashboardId":16
}
then 
curl -u admin@localhost:admin -H "Content-Type: application/json" -X PUT http://localhost:3000/api/org/preferences --data @org.json

If these steps can be confirmed we could add this to the dashUpdater code.
@zmc when you get a chance can you please confirm the above

**Comment by zmc** [comment]
```
$ curl -u admin:admin http://XXX:3000/api/dashboards/db/ceph-at-a-glance | jq '.["dashboard"]["id"]'
12
$ curl -u admin:admin -X POST -H "Content-Type: application/json" http://XXX:3000/api/user/stars/dashboard/12
{"message":"Failed to star dashboard"}
```

**Comment by pcuzner** [comment]
@zmc I've updated dashUpdater to handle this now. will push tommorrow

**Comment by pcuzner** [comment]
commit 97725264c025721e78a04dee2fd889a0021b7e35 adds this functionality
