### ISSUE TITLE
health alert only triggers on first state change

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephmetrics#217]
The health alert trigger uses >0. When health changes to 1 (warn), the alert is fired, but a subsequent change from warn->error doesn't generate another alert since the value is already > 0.

This effects both the collectd and prometheus versions of cephmetrics

**Comment by zmc** [comment]
I notice that the only alert condition for that panel is for >0; perhaps if we add a second condition alerting at >1, it would fire twice? I have not tested this yet.

**Comment by pcuzner** [comment]
The threshold is matched on the first clause and so doesn't fire again in grafana - this is one of the things that works better in prom alert manager
