### ISSUE TITLE
Logging changes break collectd

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#30]
d3432caf0dc7cc7b70b73f93a84313426fc65093 broke collectd:
```
Jun 26 16:48:50 magna120 collectd[12136]: Unhandled python exception in loading module: TypeError: __init__() got an unexpected keyword argument 'log_lev
el'
```
5899e3f helps, but:
```
Jun 26 16:55:45 magna120 collectd[17899]: Unhandled python exception in loading module: IOError: [Errno 13] Permission denied: '/var/log/collectd-cephmetrics-OSDs.log'
```

**Comment by b-ranto** [comment]
This should be fixed by https://github.com/ceph/cephmetrics/pull/28/commits/5899e3f5026e0d76aed01ec260ccc43ba8e66e29

**Comment by zmc** [comment]
That's the same commit; my comment mentioned the sha1 before it was merged to master. Updated.

**Comment by b-ranto** [comment]
Ah, sry, missed the second part of the comment.
