### ISSUE TITLE
ceph-rgw-workload: Average Request Latency reports Internal Server Error

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#40]
On a fresh production cluster:
<img width="1118" alt="screen shot 2017-06-27 at 1 37 32 pm" src="https://user-images.githubusercontent.com/58307/27606513-e3082fe0-5b3d-11e7-9703-2ef442c422c5.png">

**Comment by pcuzner** [comment]
@zmc was this seen at the soon after the environment came up? The queries use division, so I'm wondering if this was a divide by 0 issue. Right now, the graph is fine.

If you see it again, can you click on the red icon and capture the trace it shows

**Comment by zmc** [comment]
@pcuzner You're right, it looks fine now!
