### ISSUE TITLE
Carbon disk IO causing grafana updates to time out

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#45]
@pcuzner noticed that on a 10-node cluster, the cephmetrics host was saturating its (spinning) disk's IO capabilities. I noticed that grafana updates were often taking >10s, resulting in their being aborted due to the 10s refresh rate on the dashboards.

**Comment by zmc** [comment]
I'm experimenting with setting `WHISPER_AUTOFLUSH = True` in `/etc/carbon/carbon.conf`.

So far I've noticed that each grafana request (monitoring via Chrome's Developer Tools) went from taking 6-11s down to 300-800ms(!) and are no longer being aborted.

Perhaps we want to use this configuration setting?

**Comment by pcuzner** [comment]
Great find! Yes, include this in the config of the graphite deployment as a default.

In our case, we're still @ 98% util - but with this setting, it proves support for 10 hosts/54 osd's on a single spindle :smile:
