### ISSUE TITLE
Odd per-host metrics counts

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#46]
I wonder if this might partially explain https://github.com/ceph/cephmetrics/issues/45

```
$ curl -o /tmp/metrics_index.json http://magna010.ceph.redhat.com:8080/metrics/index.json
$ for i in $(seq 119 128); do host=magna$i; echo -n $host; jq '.' /tmp/metrics_index.json | grep "^ *\"collectd\.$host" | wc -l; done
magna119      93
magna120      93
magna121      93
magna122      93
magna123     169
magna124     157
magna125     157
magna126     516
magna127     516
magna128     532
```

**Comment by zmc** [comment]
That cluster is the real-world one we've been testing on for a couple weeks. On the empty one I deployed yesterday:
```
magna060     215
magna066     215
magna073     227
```

**Comment by pcuzner** [comment]
@zmc the count differs because of the role. For example, on magna126-128, it's gathering osd and mon metrics, whereas on magna119-125 are osd's with 123 being osd+rgw

**Comment by zmc** [comment]
ok, just checking. Thanks!
