### ISSUE TITLE
Weirdness in at-a-glance growth rate and weeks remaining

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#55]
<img width="252" alt="screen shot 2017-06-30 at 2 33 20 pm" src="https://user-images.githubusercontent.com/58307/27753038-2ec6a488-5da1-11e7-93bc-5a381e5a373f.png">

**Comment by pcuzner** [comment]
This should no longer occur. @zmc Can you please on latest dashboards, and close if resolved.

**Comment by pcuzner** [comment]
closing as no longer seen in Sepia demo environment
