### ISSUE TITLE
Documentation changes needed

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephmetrics#59]
The README makes a number of assumptions on the reader and should be updated to reflect

1. Repo needs to be added before installing cephmetrics-ansible (i.e. swap yum install cephmetrics-ansible and curl -L <...>)
2. I think we ought to assume that users will have ceph-ansible already and thus require that playbook to be run from the same machine. That removes the need to add rhel-7-server-rhscon-2-installer-rpms and create a new inventory file, simplifying the ansible command to: ansible-playbook -v playbook.yml
3. Doc should specify the URL for Grafana after deployment.
4. Doc should specify that all the hosts should be able to resolve the grafana host.

Thanks to Alexandre Marangone for the feedback

**Comment by zmc** [comment]
@pcuzner I'm working on addressing these. But isn't item 4 covered by "All hosts must share the same DNS domain" ?

**Comment by zmc** [comment]
re: item 2, I can modify #62 to no longer mention the option of initiating deployment from the dashboard host, if we want.

**Comment by zmc** [comment]
#60 handles the DNS issue
