### ISSUE TITLE
selinux deployment problem

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephmetrics#63]
Internal testing has shown a problem with deploying the selinux policy
fatal: [ip-172-31-40-85]: FAILED! => {"changed": true, "cmd": ["semodule", "-i", "/tmp/cephmetrics.pp"], "delta": "0:00:12.218719", "end": "2017-07-11 17:34:41.236180", "failed": true, "rc": 1, "start": "2017-07-11 17:34:29.017461", "stderr": "Failed to resolve typeattributeset statement at /etc/selinux/targeted/tmp/modules/400/cephmetrics/cil:3\nsemodule:  Failed!", "stdout": "", "stdout_lines": [], "warnings": []}

ref. http://perf1.perf.lab.eng.bos.redhat.com/bengland/tmp/cephmetrics-ansible.log

**Comment by bengland2** [comment]
Last time I ran it, it worked, am having trouble reproducing problem now.   May have been caused by an earlier failure in ansible that I corrected with use_epel: true.  I'll get back to you on this when I can pin it down farther.

**Comment by bengland2** [comment]
This is not reproducible, want to close it.

**Comment by pcuzner** [comment]
Closing as per request
