### ISSUE TITLE
num_osd_hosts is calculated incorrectly

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephmetrics#66]
the mon collector is counting the hosts listed in osd tree output to determine the number of physical hosts - but this is flawed when crush is used to create separate pools - the same physical host can appear multiple times.

**Comment by zmc** [comment]
Perhaps just use a `set()` instead of a list here https://github.com/ceph/cephmetrics/blob/master/collectors/mon.py#L210-L211 ?

**Comment by pcuzner** [comment]
The issue is that the name used in crushmap is just a logical name - not a physical host. 

The OSD collector could count the osd's it has and store that to graphite. The OSD hosts panel can then count the number of metrics that contain the osd_count to determine the OSD host count - with a countSeries query.

**Comment by pcuzner** [comment]
fixed in #79
