### ISSUE TITLE
Add a per-host filter on OSD node detail?

### ISSUE THREAD

**Issue by alram** [ceph/cephmetrics#70]
On a cluster with a large number of hosts (36 in that case), the data can be very difficult to read. I'm not sure adding a per host filter is the right solution however.

![grafana1](https://user-images.githubusercontent.com/660521/28182824-2df69b64-67c2-11e7-97ba-baabcc57844f.png)
![grafana2](https://user-images.githubusercontent.com/660521/28182834-35b21586-67c2-11e7-8152-4e42098d2f71.png)

**Comment by zmc** [comment]
Good point. With 95 osds:
<img width="1113" alt="screen shot 2017-07-13 at 1 35 17 pm" src="https://user-images.githubusercontent.com/58307/28184324-3427a9a2-67d0-11e7-99b9-c4496822e540.png">

**Comment by zmc** [comment]
In the past I've created dashboards, that are implemented in JavaScript instead of JSON, which take arguments. Here is [an example](https://github.com/ceph/ceph-cm-ansible/blob/master/roles/pcp/files/index.js). I could see us providing a JSON dashboard containing links to JS-generated dashboards which each detail a single node - if that'd be useful.

**Comment by pcuzner** [comment]
you know you can click on a drive name to just show a single drive though right? And 95 osd's on a single nodes is just shy of madness..

But yes I agree! With a lot of osd's on a node the graph is just not funny. 

We can fix it though
![grafana - osd node detail](https://user-images.githubusercontent.com/3703087/28198140-db5be92e-68af-11e7-80a6-9c8acc5c9ff6.png)

Does that work for you guys? @zmc @alram

**Comment by alram** [comment]
I think it just might. Thanks. 
When I click on a drive though is there a way to know which host it's on? In the graph I uploaded, we have 36 hosts with 12 OSDs eachs so that might be a bit tricky

**Comment by pcuzner** [comment]
I think the penny has dropped. So you're going straight to the osd node detail dashboard?

If so, the osd_servers variable is all nodes - which is why you see the picasso. We can expose the osd_server value too on this dashboard, so you can pick which your interested in

**Comment by pcuzner** [comment]
osd-node-detail dashboard in #90 now provides this level of functioality
