### ISSUE TITLE
RHSC Compatibility

### ISSUE THREAD

**Issue by scheuk** [ceph/cephmetrics#76]
After upgrading our cluster from Ceph 1.3 to 2.3 we now have RHSC installed.
It does roughly the same thing that this project does (collectd and graphite).
If I wanted to use this project instead of RHSC should it be setup against hosts that don't have any connection to a RHSC?

**Comment by pcuzner** [comment]
@scheuk cephmetrics is just monitoring, so it depends what your goals are. 

Although RHSC uses collectd/graphite I haven't done any side by side deployments to know whether they can co-exist. It should be OK - the metrics sent to graphite are named differently for example but it's not been tested AFAIK

**Comment by scheuk** [comment]
Sounds good, we decided to install it without RHSC.
