### ISSUE TITLE
Implement bluestore support in the osd collector

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephmetrics#78]
The osd collector provides OS and OSD level performance metrics for filestore based OSDs, but only os level metrics for bluestore OSDs.

Bluestore metrics should be exposed within the cephmetrics dashboards

**Comment by bengland2** [comment]
See [this comment](https://github.com/ceph/cephmetrics/issues/77#issuecomment-322446172) .  For how to get it to deploy.  But I'm sure there are other things that need to change too.  In Ceph OSD information dashboard, it assumes you are running filestore.

**Comment by pcuzner** [comment]
Yep - working on that next :) The osd information dashboard exposes filestore related metrics currently. I'll be adding a separate row for bluestore performance metrics, and need to look at how I determine disk capacity since the same metrics are not present between the two backends.

**Comment by bengland2** [comment]
in "OSD Node Detail" dashboard, it also assumes you are using disks.   Maybe we should call them "storage devices" or "block devices" or something like that.  

Also, it seems to ignore devices where SSD journal/block.wal/block.db live.

**Comment by bengland2** [comment]
re .-2: can you ask the OSD how much space it has?  I don't see a way.  Seems like bluestore would have to provide this info since there is no mountable filesystem you can query anymore.

**Comment by bengland2** [comment]
ceph osd status command seems to have this information.

    [root@ip-172-31-30-186 ~]# ceph osd status
    +----+---------------------------------------------+-------+-------+--------+---------+--------+---------+
    | id |                     host                    |  used | avail | wr ops | wr data | rd ops | rd data |
    +----+---------------------------------------------+-------+-------+--------+---------+--------+---------+
    | 0  | ip-172-31-21-197.us-west-2.compute.internal | 6879M |  533G |    0   |     0   |    0   |     0   |
    | 1  |  ip-172-31-23-66.us-west-2.compute.internal | 5880M |  534G |    0   |     0   |    0   |     0   |
    ...
    | 7  | ip-172-31-21-197.us-west-2.compute.internal | 7813M |  532G |    0   |     0   |    0   |     0   |

**Comment by pcuzner** [comment]
Bluestore support is provided by PR #100
