### ISSUE TITLE
CentOS compatibility

### ISSUE THREAD

**Issue by Daniel-Pivonka** [ceph/cephmetrics#82]
i have a hyper converged cloud deployed via tripleo quickstart with 3 controllers and 3 osd compute nodes and I've attempted to deploy cephmetrics via ansible but it failed.  The nodes are based on centos images and not rhel images so the install fails because the playbook uses the subscription-manager to do something which is not possible on a centos image i believe. is there a way around this? i can provide more information if necessary.

**Comment by scheuk** [comment]
Dan from the code,
If you setup the upstream repos manually you can run it with --skip-tags repos 
which tells ansible to skip installing the repos 
Or in ansible terms, any ansibe tasks with the label of repos

**Comment by pcuzner** [comment]
@Daniel-Pivonka can you confirm that this issue is resolved please?

**Comment by zmc** [comment]
Please reopen if this is still an issue
