### ISSUE TITLE
collectd-ping and collectd-disk don't get installed on collectd hosts

### ISSUE THREAD

**Issue by scheuk** [ceph/cephmetrics#85]
After the initial deploy, collectd did not start with an error about missing ping.
After some troubleshooting the ping collector was not installed, we installed the collectd-ping and collectd-disk packages and collectd was able to start.
here's the ansible tasks we added to install those:

``` git diff ansible/roles/ceph-collectd/tasks/install_packages.yml
diff --git a/ansible/roles/ceph-collectd/tasks/install_packages.yml b/ansible/roles/ceph-collectd/tasks/install_packages.yml
index b290ac3..25f70c1 100644
--- a/ansible/roles/ceph-collectd/tasks/install_packages.yml
+++ b/ansible/roles/ceph-collectd/tasks/install_packages.yml
@@ -17,6 +17,26 @@
     - not use_epel
   notify: Restart collectd

+- name: Install collectd-ping
+  package:
+    name: collectd-ping
+    state: latest
+  when:
+    - ansible_pkg_mgr == "yum"
+    - devel_mode
+    - not use_epel
+  notify: Restart collectd
+
+- name: Install collectd-disk
+  package:
+    name: collectd-disk
+    state: latest
+  when:
+    - ansible_pkg_mgr == "yum"
+    - devel_mode
+    - not use_epel
+  notify: Restart collectd
+
 - name: Install cephmetrics-collectors
   package:
     name: cephmetrics-collectors```

**Comment by pcuzner** [comment]
I'm not sure where this requirement is coming from. The metrics used in the dashboard don't use collectd-disk or collectd-ping data. However, I know that at least the ping plugin was used for Tendrl (Red Hat Storage Console v2). Assigning to Zack to comment

**Comment by scheuk** [comment]
I bet these were left over from the collectd install and setup from RHSC.
When I test again, I'll make sure to clean up /etc/collectd and /etc/collectd.d/* before install cephmetrics again.

**Comment by zmc** [comment]
We don't have `collectd-disk` or `collectd-ping` installed anywhere I've tested cephmetrics, and I haven't seen these errors. Looks like a left-over configuration.
