### ISSUE TITLE
Increase auto-refresh delay on dashboards?

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#9]
Refreshing every 10s can generate a considerable amount of load

**Comment by pcuzner** [comment]
Where are you seeing the load issue?

**Comment by zmc** [comment]
Well, when I logged in this morning one cluster I've been testing on had all cores at 100% - not sure what httpd was doing, but the effect lingered even after I closed all Grafana tabs.

**Comment by pcuzner** [comment]
Wow. So to clarify;
- the issue you saw was on the monitoring host, not the ceph nodes?
- the 100% cpu was attributed to httpd? Grafana just has one process grafana-server and Graphite uses nginx not httpd...so I'm a little confused.

**Comment by zmc** [comment]
* The monitor host, yes
* Well, the graphite-web packages shipped by EPEL - and also eventually us - use httpd :-/

**Comment by pcuzner** [comment]
Great...well not really :cry: 

Dumb questions follow;
- collectd sends data to carbon-cache, so I'm assuming that's OK - if so then the send rate and metrics volume is fine.
- just looking at my tinpot system and nginx basically does nothing - so why httpd works differently has me at a loss.
- Is the graphite data on flash or regular hdd? If hdd, what's the disk utilisation look like?
- maybe there is some tuning we need to do in carbon, to satisfy the requests quicker...

Anyway, can you send me login info, so I can take a deeper look.

**Comment by zmc** [comment]
* Yeah, I see no evidence of problems with the send rate at all
* Ditto
* In each of the two clusters I'm testing on, they're on spinners. But iotop looked mostly idle when the CPU issues were presenting.
* Possibly. Or it's an apache bug...

You should have access to the internal cluster I'm using; for the one in Sepia, you'd have to follow this process: https://github.com/ceph/sepia/blob/master/doc/adding_users.rst#requesting-lab-access

If you ping me when you get online we can make sure you have the access you need.

**Comment by pcuzner** [comment]
@zmc are you still seeing this as an issue?

**Comment by zmc** [comment]
I haven't been, actually. I think we can close this. If I see it again I'll reopen.
