### ISSUE TITLE
gracefully handling single OSD failure

### ISSUE THREAD

**Issue by scheuk** [ceph/cephmetrics#91]
I just had an issue with one OSD on a data node where it didn't respond to perf dump on it's admin socket. This caused the error message from collectd, which caused no stats to be collected.
I wonder if there could be some better logic around failures of collecting 'perf dump'

```Aug 05 07:01:07  collectd[84657]: Unhandled python exception in read callback: AttributeError: 'NoneType' object has no attribute 'get'
Aug 05 07:01:07  collectd[84657]: read-function of plugin `python.cephmetrics' failed. Will suspend it for 320.000 seconds.
Aug 05 07:06:27  collectd[84657]: Unhandled python exception in read callback: AttributeError: 'NoneType' object has no attribute 'get'
Aug 05 07:06:27  collectd[84657]: read-function of plugin `python.cephmetrics' failed. Will suspend it for 640.000 seconds. ```

**Comment by pcuzner** [comment]
@scheuk Thanks for raising the issue. I'll look it into. I need to complete some other work first, so it may take a couple of days.

**Comment by pcuzner** [comment]
@scheuk I have a change nearly ready to submit for this. Basically the absence of the OSD's socket will no longer raise an exception, but instead flag an error to the collectors log file and to collectd's.

Does this sound like a reasonable way to deal with this?

**Comment by pcuzner** [comment]
PR #100 should handle this issue

**Comment by scheuk** [comment]
@pcuzner that sounds good, but what if the socket exists and the process is not responding to perf dump, like the OSD is busy? IE you run `ceph ... perf dump` but it just hangs and never completes.

**Comment by pcuzner** [comment]
@scheuk so what you're asking for is effectively a timeout on a perf dump call? The admin_socket interaction is provided by a base class, so if we change that to timeout we'll get the same timeout behaviour across mon/rgw and osd interactions. If you can confirm this is what you need to address issues you see in you clusters, I'll add to the backlog (projects -> feature roadmap) tracker

**Comment by scheuk** [comment]
@pcuzner yes looking for a timeout on the perf dump call, that's what I'm looking for.

**Comment by pcuzner** [comment]
Cool - checkout the feature plan https://github.com/ceph/cephmetrics/projects/3 

the timeout is listed in the ideas section. Not sure you can add directly, but if you have things you'd like to see try to add to the ideas board, and if that doesn't work raise an issue and document it that way

**Comment by pcuzner** [comment]
@scheuk can you try using the base.py module from the add-timeout branch in your environment to see if this addresses the hanging perf dump issue?

**Comment by scheuk** [comment]
@pcuzner we managed to clear up the problem with timing out OSDs, I don't know if I can re-replicate the problem

**Comment by pcuzner** [comment]
closing - please reopen if the issue re-occurs
