### ISSUE TITLE
allowing all dashboards to reference a user-specified time range

### ISSUE THREAD

**Issue by bengland2** [ceph/cephmetrics#99]
I couldn't get all dashboards to restrict the time range to a specified interval, but if you click on a widget within a dashboard and it takes you to another one, the time range is preserved, so there is inconsistent behavior.  Even with relative time ranges, if you change it in one dashboard it isn't changed in the others. 
 Why is this important?  Let's say I have a test result, or there was a performance problem at a site reported at a certain time - we'd like to be able to look at what happened around that time, from a variety of perspectives = dashboards.    But [grafana documentation here](http://docs.grafana.org/reference/timerange/) just says no, see last sentence.

For example, a link [like this one](http://ec2-54-186-170-79.us-west-2.compute.amazonaws.com:3000/dashboard/db/ceph-at-a-glance?orgId=1&from=1502946000000&to=1503025200000) will take you to a particular time interval for a particular dashboard - this one was for yesterday.  You can either use the time range GUI or you can calculate using python by computing start and end time since 1970 in sec (what time.time() returns) multiplying by 1000 and converting to int.

I was talking with folks in IRC #rhos-scale, where Browbeat developers (OpenStack's collectd-grafana package) are, about this.  One of them ("throck" = Tom Throckmorton)  directed me to this grafana issue, which may be a chunk of the problem.  Here's [my comment](https://github.com/grafana/grafana/issues/1959#issuecomment-323433352) on this issue.

**Comment by pcuzner** [comment]
It's inconsistent in that there isn't an overarching time window that every dashboard will honour. However, all the linked dashboards (i think) from at-a-glance pass through the time window - so is it not possible to select the time range from at-a-glance, and then link from there to the other dashboards given I pass the time window across? Each linked dashboard opens a new tab so you can switch between tabs to view the different perspectives on the same time range.

**Comment by pcuzner** [comment]
The above workaround has been discussed, and since there is nothing cephmetrics can do to fix this, I'm closing the issue
